### ISSUE TITLE
IPAPI-Mz.js 不显示 emoji

### ISSUE THREAD

**Issue by xixaxoqiqaqo** [Mazeorz/QuantumultX#1]
- IPAPI-Mz.js 不显示 emoji, 字体也还是一样的？

**Comment by Mazeorz** [comment]
![D73FB5A4-FF93-411D-A92A-A101230FEC01](https://user-images.githubusercontent.com/67795943/109331816-44d36980-7898-11eb-984e-7ee90a043d7b.png)
截图看看

**Comment by xixaxoqiqaqo** [comment]
商店版:1.0.19
![F8AEE314-E0E5-4F57-A12C-4034DF72033F](https://user-images.githubusercontent.com/78405720/109375216-02407a00-78f6-11eb-8dde-7fb6472aca0b.jpeg)

**Comment by Mazeorz** [comment]
@Mazeorz tg联系看看

**Comment by xixaxoqiqaqo** [comment]
- 我原先只替换了链接，刚才我直接复制geo_location_checker=http://ip-api.com/json/?lang=en-us, https://raw.githubusercontent.com/Mazeorz/QuantumultX/main/Scripts/IPAPI-Mz.js
- 好了，可能是因为我替换垃圾的时候把 http://ip-api.com/json/?lang=zh-CN 给去掉了
- 也有可能是 ?lang=zh-CN 没有改成 en-US
- 挺好看的
